//carga variables de entorno por si el seed se ejecuta directo con node
require("dotenv").config();
//reutiliza el cliente de Prisma configurado con el driver adapter
const prisma = require("../src/prisma/prismaClient");

//datos iniciales: equipos del fútbol argentino, coherentes con la temática de la app
const teams = [
  {
    name: "Boca Juniors",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Alberto J. Armando (La Bombonera)",
    founded: 1905,
    coach: "Claudio Úbeda",
    shortDescription: "Uno de los clubes más populares de Argentina, dueño de La Bombonera.",
    description:
      "El Club Atlético Boca Juniors fue fundado en 1905 en el barrio de La Boca. Es uno de los equipos más ganadores del fútbol argentino y un habitual protagonista de la Copa Libertadores, con una de las hinchadas más numerosas del país.",
    logo: "/logos/boca.png",
    image: "/images/boca.jpg",
    category: "Primera División",
    titles: 35,
  },
  {
    name: "River Plate",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Más Monumental",
    founded: 1901,
    coach: "Marcelo Gallardo",
    shortDescription: "El club más ganador de la liga argentina, juega en el Monumental.",
    description:
      "El Club Atlético River Plate fue fundado en 1901. Es el máximo ganador de campeonatos de liga en Argentina y su estadio, el Más Monumental, es el de mayor capacidad de Sudamérica.",
    logo: "/logos/river.png",
    image: "/images/river.jpg",
    category: "Primera División",
    titles: 38,
  },
  {
    name: "Racing Club",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Presidente Perón (El Cilindro)",
    founded: 1903,
    coach: "Gustavo Costas",
    shortDescription: "La Academia de Avellaneda, primer campeón mundial argentino.",
    description:
      "Racing Club fue fundado en 1903 en Avellaneda. Conocido como La Academia, fue el primer club argentino en consagrarse campeón del mundo en 1967 y disputa el clásico de Avellaneda con Independiente.",
    logo: "/logos/racing.png",
    image: "/images/racing.jpg",
    category: "Primera División",
    titles: 18,
  },
  {
    name: "Independiente",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Libertadores de América",
    founded: 1905,
    coach: "Julio Vaccari",
    shortDescription: "El Rey de Copas, máximo ganador histórico de la Copa Libertadores entre los argentinos.",
    description:
      "El Club Atlético Independiente fue fundado en 1905 en Avellaneda. Apodado el Rey de Copas por sus siete Copas Libertadores, es uno de los cinco grandes del fútbol argentino.",
    logo: "/logos/independiente.png",
    image: "/images/independiente.jpg",
    category: "Primera División",
    titles: 16,
  },
  {
    name: "San Lorenzo",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Pedro Bidegain (Nuevo Gasómetro)",
    founded: 1908,
    coach: "Damián Ayude",
    shortDescription: "El Ciclón de Boedo, uno de los cinco grandes del fútbol argentino.",
    description:
      "San Lorenzo de Almagro fue fundado en 1908. Campeón de la Copa Libertadores 2014, disputa sus partidos en el Nuevo Gasómetro y mantiene una histórica identidad con el barrio de Boedo.",
    logo: "/logos/sanlorenzo.png",
    image: "/images/sanlorenzo.jpg",
    category: "Primera División",
    titles: 15,
  },
  {
    name: "Vélez Sarsfield",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "José Amalfitani",
    founded: 1910,
    coach: "Guillermo Barros Schelotto",
    shortDescription: "El Fortín de Liniers, campeón de América en 1994.",
    description:
      "El Club Atlético Vélez Sarsfield fue fundado en 1910. Su época dorada llegó en los años noventa de la mano de Carlos Bianchi, con la Copa Libertadores y la Intercontinental de 1994.",
    logo: "/logos/velez.png",
    image: "/images/velez.jpg",
    category: "Primera División",
    titles: 10,
  },
  {
    name: "Estudiantes de La Plata",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Jorge Luis Hirschi",
    founded: 1905,
    coach: "Eduardo Domínguez",
    shortDescription: "El Pincha, tricampeón de América entre 1968 y 1970.",
    description:
      "Estudiantes de La Plata fue fundado en 1905. Ganó tres Copas Libertadores consecutivas entre 1968 y 1970 y una cuarta en 2009, y es reconocido por su histórica garra y pergaminos coperos.",
    logo: "/logos/estudiantes.png",
    image: "/images/estudiantes.jpg",
    category: "Primera División",
    titles: 6,
  },
  {
    name: "Gimnasia y Esgrima La Plata",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Juan Carmelo Zerillo (El Bosque)",
    founded: 1887,
    coach: "Fernando Zaniratto",
    shortDescription: "El Lobo platense, el club más antiguo del fútbol argentino en actividad.",
    description:
      "Gimnasia y Esgrima La Plata fue fundado en 1887, lo que lo convierte en uno de los clubes más antiguos de América. Disputa el clásico platense con Estudiantes y juega en el estadio del Bosque.",
    logo: "/logos/gimnasia.png",
    image: "/images/gimnasia.jpg",
    category: "Primera División",
    titles: 1,
  },
  {
    name: "Newell's Old Boys",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Marcelo Alberto Bielsa (El Coloso)",
    founded: 1903,
    coach: "Cristian Fabbiani",
    shortDescription: "La Lepra rosarina, cuna de Messi, Bielsa y grandes ídolos.",
    description:
      "Newell's Old Boys fue fundado en 1903 en Rosario. De su cantera salieron futbolistas como Lionel Messi y entrenadores como Marcelo Bielsa, y disputa el clásico rosarino con Rosario Central.",
    logo: "/logos/newells.png",
    image: "/images/newells.jpg",
    category: "Primera División",
    titles: 6,
  },
  {
    name: "Rosario Central",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Gigante de Arroyito",
    founded: 1889,
    coach: "Ariel Holan",
    shortDescription: "El Canalla, dueño del Gigante de Arroyito.",
    description:
      "Rosario Central fue fundado en 1889 por trabajadores del ferrocarril. Es uno de los clubes más importantes del interior del país y protagonista del clásico rosarino frente a Newell's.",
    logo: "/logos/central.png",
    image: "/images/central.jpg",
    category: "Primera División",
    titles: 4,
  },
  {
    name: "Talleres de Córdoba",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Mario Alberto Kempes",
    founded: 1913,
    coach: "Carlos Tevez",
    shortDescription: "La T cordobesa, animador habitual de los torneos recientes.",
    description:
      "El Club Atlético Talleres fue fundado en 1913 en Córdoba. En los últimos años se consolidó como protagonista de la Liga Profesional y participante frecuente de las copas internacionales.",
    logo: "/logos/talleres.png",
    image: "/images/talleres.jpg",
    category: "Primera División",
    titles: 0,
  },
  {
    name: "Belgrano",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Julio César Villagra (Gigante de Alberdi)",
    founded: 1905,
    coach: "Ricardo Zielinski",
    shortDescription: "El Pirata de Córdoba, dueño del Gigante de Alberdi.",
    description:
      "El Club Atlético Belgrano fue fundado en 1905 en el barrio de Alberdi, Córdoba. Disputa el clásico cordobés con Talleres y es recordado por eliminar a River en la promoción de 2011.",
    logo: "/logos/belgrano.png",
    image: "/images/belgrano.jpg",
    category: "Primera División",
    titles: 0,
  },
  {
    name: "Argentinos Juniors",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Diego Armando Maradona",
    founded: 1904,
    coach: "Nicolás Diez",
    shortDescription: "El Semillero del Mundo, club donde debutó Diego Maradona.",
    description:
      "La Asociación Atlética Argentinos Juniors fue fundada en 1904 en La Paternal. Es famosa por su cantera, de la que surgieron Diego Maradona, Juan Román Riquelme y Fernando Redondo, y ganó la Copa Libertadores en 1985.",
    logo: "/logos/argentinos.png",
    image: "/images/argentinos.jpg",
    category: "Primera División",
    titles: 3,
  },
  {
    name: "Huracán",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Tomás Adolfo Ducó (El Palacio)",
    founded: 1908,
    coach: "Frank Darío Kudelka",
    shortDescription: "El Globo de Parque Patricios, dueño del Palacio Ducó.",
    description:
      "El Club Atlético Huracán fue fundado en 1908 en Parque Patricios. Su campaña de 1973, con César Luis Menotti como técnico, es recordada como una de las más brillantes del fútbol argentino.",
    logo: "/logos/huracan.png",
    image: "/images/huracan.jpg",
    category: "Primera División",
    titles: 1,
  },
  {
    name: "Lanús",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Ciudad de Lanús (La Fortaleza)",
    founded: 1915,
    coach: "Mauricio Pellegrino",
    shortDescription: "El Granate del sur, campeón de la Sudamericana en dos ocasiones.",
    description:
      "El Club Atlético Lanús fue fundado en 1915. En las últimas dos décadas se convirtió en un equipo protagonista, con títulos locales y dos Copas Sudamericanas en sus vitrinas.",
    logo: "/logos/lanus.png",
    image: "/images/lanus.jpg",
    category: "Primera División",
    titles: 2,
  },
  {
    name: "Banfield",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Florencio Sola",
    founded: 1896,
    coach: "Pedro Troglio",
    shortDescription: "El Taladro, campeón del Apertura 2009.",
    description:
      "El Club Atlético Banfield fue fundado en 1896 por la comunidad británica del sur del Gran Buenos Aires. Su mayor logro fue el torneo Apertura 2009, el primer título de liga de su historia.",
    logo: "/logos/banfield.png",
    image: "/images/banfield.jpg",
    category: "Primera División",
    titles: 1,
  },
  {
    name: "Tigre",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "José Dellagiovanna",
    founded: 1902,
    coach: "Diego Dabove",
    shortDescription: "El Matador de Victoria, finalista de la Libertadores de la zona norte.",
    description:
      "El Club Atlético Tigre fue fundado en 1902. Campeón de la Copa de la Superliga 2019, es el equipo más representativo de la zona norte del Gran Buenos Aires.",
    logo: "/logos/tigre.png",
    image: "/images/tigre.jpg",
    category: "Primera División",
    titles: 0,
  },
  {
    name: "Platense",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Ciudad de Vicente López",
    founded: 1905,
    coach: "Cristian González",
    shortDescription: "El Calamar de Vicente López, campeón del Apertura 2025.",
    description:
      "El Club Atlético Platense fue fundado en 1905. Tras décadas de lucha entre el ascenso y la primera división, conquistó en 2025 el primer título de liga de su historia.",
    logo: "/logos/platense.png",
    image: "/images/platense.jpg",
    category: "Primera División",
    titles: 1,
  },
  {
    name: "Defensa y Justicia",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Norberto Tomaghello",
    founded: 1935,
    coach: "Mariano Soso",
    shortDescription: "El Halcón de Varela, campeón de la Sudamericana 2020.",
    description:
      "Defensa y Justicia fue fundado en 1935 en Florencio Varela. En 2020 y 2021 vivió su época dorada al ganar la Copa Sudamericana y la Recopa Sudamericana.",
    logo: "/logos/defensa.png",
    image: "/images/defensa.jpg",
    category: "Primera División",
    titles: 2,
  },
  {
    name: "Godoy Cruz",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Malvinas Argentinas",
    founded: 1921,
    coach: "Walter Ribonetto",
    shortDescription: "El Tomba mendocino, habitual participante de copas internacionales.",
    description:
      "Godoy Cruz Antonio Tomba fue fundado en 1921 en Mendoza. Desde su ascenso en 2006 se afianzó en la máxima categoría y clasificó en varias ocasiones a la Copa Libertadores y la Sudamericana.",
    logo: "/logos/godoycruz.png",
    image: "/images/godoycruz.jpg",
    category: "Primera División",
    titles: 0,
  },
  {
    name: "Unión de Santa Fe",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "15 de Abril",
    founded: 1907,
    coach: "Leonardo Madelón",
    shortDescription: "El Tatengue, protagonista del clásico santafesino.",
    description:
      "El Club Atlético Unión fue fundado en 1907 en la ciudad de Santa Fe. Disputa con Colón uno de los clásicos más apasionados del interior del país.",
    logo: "/logos/union.png",
    image: "/images/union.jpg",
    category: "Primera División",
    titles: 0,
  },
  {
    name: "Colón",
    country: "Argentina",
    league: "Primera Nacional",
    stadium: "Brigadier General Estanislao López",
    founded: 1905,
    coach: "Ezequiel Medrán",
    shortDescription: "El Sabalero santafesino, campeón de la Copa de la Liga 2021.",
    description:
      "El Club Atlético Colón fue fundado en 1905 en Santa Fe. En 2021 logró el primer título de liga de su historia y actualmente pelea por volver a la máxima categoría.",
    logo: "/logos/colon.png",
    image: "/images/colon.jpg",
    category: "Primera Nacional",
    titles: 1,
  },
  {
    name: "Atlético Tucumán",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Monumental José Fierro",
    founded: 1902,
    coach: "Lucas Pusineri",
    shortDescription: "El Decano del norte argentino.",
    description:
      "El Club Atlético Tucumán fue fundado en 1902 y es el club más importante del norte argentino. Desde su ascenso en 2015 se mantiene en primera división y llegó a disputar la Copa Libertadores.",
    logo: "/logos/atleticotucuman.png",
    image: "/images/atleticotucuman.jpg",
    category: "Primera División",
    titles: 0,
  },
  {
    name: "Central Córdoba de Santiago del Estero",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Alfredo Terrera",
    founded: 1919,
    coach: "Omar De Felippe",
    shortDescription: "El Ferroviario santiagueño, campeón de la Copa Argentina 2024.",
    description:
      "Central Córdoba fue fundado en 1919 en Santiago del Estero. En 2024 dio el gran golpe al ganar la Copa Argentina, su primer título nacional, y clasificar a la Copa Libertadores.",
    logo: "/logos/centralcordoba.png",
    image: "/images/centralcordoba.jpg",
    category: "Primera División",
    titles: 1,
  },
  {
    name: "Barracas Central",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Claudio Chiqui Tapia",
    founded: 1904,
    coach: "Rubén Darío Insúa",
    shortDescription: "El Guapo del sur de la Ciudad de Buenos Aires.",
    description:
      "El Club Atlético Barracas Central fue fundado en 1904 en el barrio porteño de Barracas. Tras su ascenso en 2021 se mantiene en la máxima categoría del fútbol argentino.",
    logo: "/logos/barracas.png",
    image: "/images/barracas.jpg",
    category: "Primera División",
    titles: 0,
  },
  {
    name: "Deportivo Riestra",
    country: "Argentina",
    league: "Liga Profesional Argentina",
    stadium: "Guillermo Laza",
    founded: 1931,
    coach: "Gustavo Benítez",
    shortDescription: "El Malevo del Bajo Flores, la revelación de los últimos torneos.",
    description:
      "El Club Deportivo Riestra fue fundado en 1931 en el Bajo Flores. Tras ascender por primera vez a la máxima categoría, sorprendió al pelear los primeros puestos de la Liga Profesional.",
    logo: "/logos/riestra.png",
    image: "/images/riestra.jpg",
    category: "Primera División",
    titles: 0,
  },
];

const main = async () => {
  console.log("Iniciando seed...");
  //limpia la tabla para que el seed se pueda ejecutar varias veces sin duplicar datos
  await prisma.team.deleteMany();
  //inserta todos los equipos en la base
  const result = await prisma.team.createMany({ data: teams });
  console.log(`Seed completado: ${result.count} equipos cargados.`);
};

main()
  .catch((error) => {
    console.error("Error ejecutando el seed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
